### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [landroo/GodotMaze#1]
You mentioned in your assetlib submission that the asset is under the MIT license, but nothing shows it in this repo. Could you add a LICENSE.txt file or similar with the license text?

See http://choosealicense.com/

**Comment by landroo** [comment]
yes

**Comment by landroo** [comment]
yes

2016-09-05 17:14 GMT+02:00 Rémi Verschelde notifications@github.com:

**Comment by akien-mga** [comment]
Thanks.

**Comment by akien-mga** [comment]
BTW, I modified the download URL to point to https://github.com/landroo/GodotMaze/archive/7ea09fe8b28c5dd703d74f18fb955244a21a00a6.zip, i.e. the zip archive for the current commit. Zip archives need to be validated using sha256 to ensure that users will download what was moderated, so using `archive/master.zip` is problematic as the archive changes each time a new commit is made.

So to workaround this, it's better to use `archive/<commit>.zip` or `archive/<tag>.zip` which would not change when you push new stuff. (It also means that when you push new commits, you need to edit the asset on the assetlib to update the version/download URL - it's a bit cumbersome but it's a compromise to ensure security).
